events = [
    ["Event", "Effect Type", "Affected Aspect", "id"],
    ["Earthquakes", "Negative", ["Production Capacity"], 0], # display in frontend
    ["Hurricanes", "Negative", ["Delivery Time"], 1],
    ["Floods", "Negative", ["Order Fulfillment"], 2],
    ["Wildfires", "Negative", ["Production Capacity"], 3],
    ["Droughts", "Negative", ["Price"], 4],
    ["Tsunamis", "Negative", ["Delivery Time"], 5],
    ["Volcano eruptions", "Negative", ["Delivery Time"], 6],
    ["Severe storms", "Negative", ["Delivery Time"], 7], # display in frontend
    ["Pandemics", "Negative", ["Production Capacity"], 8],
    ["Factory closures", "Negative", ["Production Capacity"], 9],
    ["Workforce absenteeism", "Negative", ["Production Capacity"], 10], # display in frontend
    ["Recessions", "Negative", ["Demand"], 11],
    ["Inflation", "Negative", ["Price"], 12],
    ["Trade wars", "Negative", ["Price"], 13],
    ["Economic booms", "Positive", ["Demand"], 14],
    ["Wage increases", "Negative", ["Price"], 15],
    ["Labor strikes", "Negative", ["Production Capacity"], 16],
    ["Port congestion", "Negative", ["Delivery Time"], 17],
    ["Fuel shortages", "Negative", ["Delivery Time"], 18],
    ["Road closures", "Negative", ["Delivery Time"], 19],
    ["Truck driver shortages", "Negative", ["Delivery Time"], 20],
    ["Rail strikes", "Negative", ["Delivery Time"], 21],
    ["Air traffic disruptions", "Negative", ["Delivery Time"], 22],
    ["Shipping container shortages", "Negative", ["Price"], 23],
    ["New environmental regulations", "Negative", ["Price"], 24],
    ["Bans on certain materials", "Negative", ["Production Capacity"], 25],
    ["Import/export law changes", "Negative", ["Delivery Time"], 26],
    ["Tax reforms", "Positive", ["Price"], 27],
    ["Licensing delays", "Negative", ["Production Capacity"], 28],
    ["Raw material shortages", "Negative", ["Price"], 29],
    ["Discovery of abundant raw materials", "Positive", ["Price"], 30],
    ["Mining accidents", "Negative", ["Production Capacity"], 31],
    ["Water scarcity", "Negative", ["Price"], 32],
    ["Automation", "Positive", ["Production Capacity"], 33],
    ["AI implementation", "Positive", ["Production Capacity"], 34],
    ["Better forecasting tools", "Positive", ["Order Fulfillment"], 35],
    ["Drone delivery", "Positive", ["Delivery Time"], 36],
    ["Renewable energy adoption", "Positive", ["Price"], 37], # display in frontend
    ["Consumer preference shifts", "Positive", ["Demand"], 38],
    ["Seasonal demand spikes", "Positive", ["Demand"], 39],
    ["New product version launches", "Positive", ["Demand"], 40],
    ["Social media campaigns", "Positive", ["Demand"], 41],
    ["Negative publicity", "Negative", ["Demand"], 42],
    ["War", "Negative", ["Delivery Time"], 43],
    ["Sanctions", "Negative", ["Production Capacity"], 44],
    ["Political instability", "Negative", ["Delivery Time"], 45],
    ["Trade agreements", "Positive", ["Price"], 46],
    ["Border closures", "Negative", ["Delivery Time"], 47],
    ["Factory fires", "Negative", ["Production Capacity"], 48],
    ["Equipment breakdowns", "Negative", ["Production Capacity"], 49],
    ["Lean manufacturing", "Positive", ["Production Capacity"], 50],
    ["Outsourcing", "Positive", ["Price"], 51],
    ["Climate change", "Negative", ["Price"], 52],
    ["Extreme heat", "Negative", ["Production Capacity"], 53],
    ["Biodiversity loss", "Negative", ["Production Capacity"], 54],
    ["Panic buying", "Positive", ["Demand"], 55],
    ["Increased popularity", "Positive", ["Demand"], 56],
    ["New substitute", "Negative", ["Demand"], 57],
    ["Viral trends", "Positive", ["Demand"], 58],
    ["Cyberattacks", "Negative", ["Production Capacity"], 59],
    ["Supply chain software failures", "Negative", ["Delivery Time"], 60],
    ["Data breaches", "Negative", ["Demand"], 61],
    ["Blockchain implementation", "Positive", ["Production Capacity", "Delivery Time"], 62],
    ["Rising oil prices", "Negative", ["Price"], 63],
    ["Power outages", "Negative", ["Production Capacity"], 64],
    ["Electrification of fleets", "Positive", ["Price", "Delivery Time"], 65],
    ["Just-in-Time (JIT) implementation", "Positive", ["Order Fulfillment"], 66],
    ["Customer loss due to delays", "Negative", ["Demand"], 67],
    ["Premium pricing for faster delivery", "Positive", ["Price"], 68],
    ["Trade show cancellations", "Negative", ["Demand"], 69],
    ["Major sporting events", "Positive", ["Demand"], 70],
    ["Packaging shortages", "Negative", ["Production Capacity", "Delivery Time"], 71],
    ["Transportation accidents", "Negative", ["Delivery Time"], 72],
    ["New packaging", "Positive", ["Price"], 73],
    ["Market booms in emerging economies", "Positive", ["Demand"], 74],
    ["Subsidies", "Positive", ["Price"], 75],
    ["Higher taxes", "Negative", ["Price"], 76],
    ["Mergers", "Positive", ["Delivery Time"], 77],
    ["Natural gas shortages", "Negative", ["Production Capacity", "Price"], 78],
    ["Government incentives for green energy", "Positive", ["Production Capacity"], 79],
    ["Adoption of electric vehicles in logistics", "Positive", ["Delivery Time", "Price"], 80],
    ["Breakthroughs in recycling technology", "Positive", ["Order Fulfillment", "Price"], 81],
    ["Government subsidies for local manufacturing", "Positive", ["Production Capacity", "Price"], 82],
    ["Introduction of autonomous delivery systems", "Positive", ["Delivery Time"], 83],
    ["High investor trust in brand reliability", "Positive", ["Demand"], 84],
    ["Partnerships with local suppliers", "Positive", ["Delivery Time", "Production Capacity"], 85],
    ["Development of predictive maintenance systems", "Positive", ["Production Capacity"], 86],
    ["Global reduction in trade tariffs", "Positive", ["Price", "Delivery Time"], 87],
    ["Increased investment in renewable energy infrastructure", "Positive", ["Production Capacity", "Price"], 88],
    ["Advances in operation robotics", "Positive", ["Production Capacity"], 89] # display in frontend
]
